### ISSUE TITLE
unsolicited extensions

### ISSUE THREAD

**Issue by kaduk** [ekr/tls13-spec#80]
Apparently Johnathan Hoyland thinks that the current text allows for unsolicited non-request-response extensions unless specifically forbidden (e.g., for HRR), but Ekr and I think they are forbidden.  Perhaps this should be clarified.

**Comment by ekr** [comment]
https://github.com/ekr/tls13-spec/pull/new/unsolicited_responses.

Closing here as it will be handled in the other repo.
