### ISSUE TITLE
Remnant of PSK cipher suites

### ISSUE THREAD

**Issue by davidben** [ekr/tls13-spec#82]
I noticed this text in the Early Data Indication section:

> In order to accept early data, the server MUST have accepted a PSK cipher suite and selected the first key offered in the client's "pre_shared_key" extension.

I think the reference to PSK cipher suite is a remnant of when we were reusing TLS 1.2 cipher suites. I believe we can simply drop "accepted a PSK cipher suite and ".

**Comment by ekr** [comment]
This is now fixed.
